api = "0.2"

[buildpack]
id = "heroku/ruby"
version = "0.1.4"
name = "Ruby"
homepage = "https://github.com/hugeen/heroku-buildpack-ruby"
ruby_version = "2.3.8"

[publish]

[publish.Ignore]
files = ["spec/"]

[[publish.Vendor]]
url = "https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/heroku-16/ruby-2.3.8.tgz"
dir = "vendor/ruby/heroku-16"

[[stacks]]
id = "heroku-16"


[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-ruby-buildpack"
